apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: win10jp
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-large
  #http or https location of OVA without the prefix:
  imageName: ent.box.com/shared/static/yin0syvnkvmjnlcbrcsg9o4ujzcbjv46.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
