# helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-scdf
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: spring-cloud-dataflow
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "32.0.2"  # Specify the chart version here
  values:
    rabbitmq:
      persistence:
        existingClaim: "rabbitmq-pvc"
      volumePermissions:
        enabled: true
    mariadb:
      primary:
        persistence:
          existingClaim: "mariadb-pvc"
      volumePermissions:
        enabled: true
    server:
      service:
        type: NodePort
        nodePort: "31000"