apiVersion: v1
kind: Namespace
metadata:
  name: db

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgre-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/postgre-pv"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: posgresql
  name: postgresql
  namespace: db
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: postgresql
          image: bitnami/postgresql
          env:
            - name: POSTGRESQL_USERNAME
              value: "ecs_user"
            - name: POSTGRESQL_PASSWORD
              value: "VMware123"
            - name: POSTGRESQL_DATABASE
              value: "monitoring_db"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgresql-pv
      volumes:
        - name: postgresql-pv
          persistentVolumeClaim:
            claimName: postgresql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: db
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgresql
  type: ClusterIP
